### ISSUE TITLE
Canvas System Design TODO

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#808]
This is a list of canvas related TODO's that are related to how the canvas functions, not the look.

- [x] Connections use iolet bounding box, not connection path bounding box
- [ ] Objects size to be inclusive of border
Currently border is added to the external of objects. When snapping object & object resizing, an object can be snapped, but extend over it's snapped size. This makes it hard to judge how the objects will look in PD-Vanilla, and should be inside their bounds regardless.
- [ ] Larger resolution canvas coordinates
Currently, when we zoom in and perform a canvas drag, we are limited to the resolution of the canvas, even though we are at 3x the canvas resolution. This causes stepped positioning when moving the canvas around.
Specifically the coordinate space is 1:1 with PD-vanilla. However when we zoom in (300%) that space is now 1:3.
I suggest that we increase the canvas resolution to 512,000 x 512,000, and also describe objects at 4x the size. 
Thus when we zoom into the canvas, there is more resolution to perform drag move. Note: There won't be more resolution to describe object position, as that is locked to the lower resolution canvas.
- [x] Per canvas zoom (for each open canvas - no need to save this value) #832

**Comment by timothyschoen** [comment]
But you'd still have the problem of losing accuracy upon saving/loading right? And in general, any time we sync positions up to the Pd canvas.

Say the position is 401, then the Pd position would be 100, and after loading it will be 400.

**Comment by alcomposer** [comment]
Yes, this isn't about increasing the accuracy of the objects. They are always going to be locked to their coordinate space. So if we move an object into 401, it will lock to 400. 

What this would achieve is moving the canvas smoothly, without the canvas movement inside the viewport being controlled by the resolution of itself, when that resolution is no longer meaningful (when zoom is > 100%)

**Comment by timothyschoen** [comment]
Increasing accuracy for canvas is currently not planned because it would be a bit of a hassle. Maybe someday?
